name: palestine_connection
description: Lightweight internet connection test, lookup any provided domain.
version: 0.0.21

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.7.2
  test: ^1.20.1
