name: palestine_connection
description: Lightweight internet connection test, lookup any provided domain.
version: 0.0.19

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.15.0 <3.0.0"

dev_dependencies:
  lint: ^1.8.1
  test: ^1.20.1
